server.shutdown: graceful
spring.lifecycle.timeout-per-shutdown-phase: 10s

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest

management:
  endpoint:
    health:
      show-details: "ALWAYS"
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState, rabbit, db, mongo
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

---
spring.config.activate.on-profile: docker
spring.rabbitmq.host: rabbitmq
