spring:
  application:
    name: product-service

server:
  port: 7001

logging:
  level:
    root: INFO
    se.magnus.microservices: DEBUG
    org.springframework.web: DEBUG

spring.mongodb:
  host: localhost
  port: 27017
  database: product-db


---
spring.config.activate.on-profile: docker
spring.mongodb.host: mongodb
server.port: 8080