spring:
  application:
    name: product-service

server:
  port: 7001

logging:
  level:
    root: INFO
    se.magnus.microservices: DEBUG
    org.springframework.web: DEBUG

spring.mongodb:
  host: localhost
  port: 27017
  database: product-db

spring:
  cloud:
    stream:
      defaultBinder: rabbit
      default.contentType: application/json
      bindings:
        messageProcessor-in-0:
          destination: products
          group: productsGroup
      rabbit:
        bindings:
          messageProcessor-in-0:
            consumer:
              auto-bind-dlq: true
              republish-to-dlq: true
      kafka:
        binder:
          brokers: 127.0.0.1
          defaultBrokerPort: 9092

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest

---
spring.config.activate.on-profile: docker
spring.mongodb.host: mongodb
spring.rabbitmq.host: rabbitmq
spring.cloud.stream.kafka.binder.brokers: kafka
server.port: 8080