spring:
  cloud:
    gateway:
      default-filters:
        - PreserveHostHeader
      routes:
        - id: product-composite-actuator
          uri: http://product-composite
          predicates:
            - Path=/product-composite/actuator/**
          filters:
            - RewritePath=/product-composite/actuator/(?<segment>.*), /actuator/$\{segment}
        - id: product-composite
          uri: http://product-composite
          predicates:
            - Path=/product-composite/**
        - id: openapi
          uri: http://product-composite
          predicates:
            - Path=/openapi/**
        - id: config
          uri: http://${app.config-server}:8888
          predicates:
            - Path=/config/**
          filters:
            - RewritePath=/config/(?<segment>.*), /$\{segment}

server:
  port: 8443
  ssl:
    key-store: classpath:keystore/edge.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: localhost

app:
  config-server: localhost

management:
  endpoint:
    health:
      show-details: "ALWAYS"
      group:
        readiness:
          include: readinessState
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: WARN

---
spring.config.activate.on-profile: docker
app.config-server: config
